import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

function toPackageName(value) {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return normalized || 'my-earn-app';
}

function getProjectPackageJson(name) {
  const packageJson = {
    name,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      start: 'node src/index.js',
      vaults: 'node src/vaults.js',
    },
  };

  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function getProjectReadme(name) {
  return `# ${name}

Minimal LI.FI Earn starter generated by create-earn-app.

## Quickstart

1. Copy \`.env.example\` to \`.env\`
2. Add your \`LIFI_API_KEY\`
3. Install dependencies with \`npm install\`
4. Run \`npm run vaults\` to fetch top transactional vaults

## Scripts

- \`npm run vaults\`: fetch and print transactional Earn vaults
- \`npm start\`: same as \`npm run vaults\`
`;
}

function getProjectEntryPoint() {
  return `import { printTransactionalVaults } from './vaults.js';

async function main() {
  const chainId = process.env.EARN_CHAIN_ID ?? '8453';
  const asset = process.env.EARN_ASSET ?? 'USDC';
  const limit = Number(process.env.EARN_LIMIT ?? 5);

  console.log('create-earn-app starter');
  console.log('- chainId:', chainId);
  console.log('- asset:', asset);
  console.log('- limit:', limit);

  await printTransactionalVaults({ chainId, asset, limit });
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error('Failed to fetch transactional vaults:', message);
  process.exitCode = 1;
});
`;
}

function getEarnClientModule() {
  return `const EARN_BASE_URL = process.env.LIFI_EARN_BASE_URL ?? 'https://earn.li.fi';

export function getEarnHeaders() {
  const headers = {
    Accept: 'application/json',
  };

  if (process.env.LIFI_API_KEY) {
    headers['x-lifi-api-key'] = process.env.LIFI_API_KEY;
  }

  return headers;
}

export function buildEarnUrl(pathname, params = {}) {
  const url = new URL(pathname, EARN_BASE_URL);
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null || value === '') {
      continue;
    }
    url.searchParams.set(key, String(value));
  }
  return url;
}

export async function fetchEarn(pathname, params = {}) {
  const url = buildEarnUrl(pathname, params);
  const response = await fetch(url, { headers: getEarnHeaders() });

  if (!response.ok) {
    throw new Error(\`Earn request failed (\${response.status})\`);
  }

  return response.json();
}
`;
}

function getVaultsModule() {
  return `import { existsSync, readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { fetchEarn } from './earn.js';

function loadEnvFile() {
  if (!existsSync('.env')) {
    return;
  }

  const content = readFileSync('.env', 'utf8');
  const lines = content.split(/\\r?\\n/);

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();
    if (!key || key in process.env) {
      continue;
    }

    process.env[key] = value.replace(/^['"]|['"]$/g, '');
  }
}

loadEnvFile();

function normalizeVaultList(payload) {
  if (Array.isArray(payload)) {
    return payload;
  }

  if (Array.isArray(payload?.data)) {
    return payload.data;
  }

  if (Array.isArray(payload?.data?.vaults)) {
    return payload.data.vaults;
  }

  if (Array.isArray(payload?.vaults)) {
    return payload.vaults;
  }

  return [];
}

function getApy(vault) {
  const apy = vault?.apy ?? vault?.currentApy ?? vault?.depositApy;
  return typeof apy === 'number' ? apy : null;
}

function formatApy(vault) {
  const apy = getApy(vault);
  return apy === null ? 'n/a' : \`\${apy.toFixed(2)}%\`;
}

export async function listTransactionalVaults(options = {}) {
  const chainId = options.chainId ?? process.env.EARN_CHAIN_ID ?? '8453';
  const asset = options.asset ?? process.env.EARN_ASSET ?? 'USDC';
  const limit = Number(options.limit ?? process.env.EARN_LIMIT ?? 5);

  const payload = await fetchEarn('/v1/earn/vaults', {
    chainId: String(chainId),
    asset: String(asset),
    sortBy: 'apy',
    limit: String(limit),
  });

  return normalizeVaultList(payload)
    .filter((vault) => Boolean(vault?.isTransactional))
    .slice(0, limit);
}

export async function printTransactionalVaults(options = {}) {
  const vaults = await listTransactionalVaults(options);

  if (vaults.length === 0) {
    console.log('No transactional vaults found.');
    return;
  }

  console.log('Top transactional vaults:');
  for (const vault of vaults) {
    const name = vault?.name ?? vault?.symbol ?? 'Unnamed vault';
    const protocol = vault?.protocolName ?? vault?.protocol ?? 'unknown protocol';
    console.log(\`- \${name} | \${protocol} | APY \${formatApy(vault)}\`);
  }
}

function isDirectRun() {
  if (!process.argv[1]) {
    return false;
  }

  return import.meta.url === pathToFileURL(process.argv[1]).href;
}

if (isDirectRun()) {
  printTransactionalVaults().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error('Failed to fetch transactional vaults:', message);
    process.exitCode = 1;
  });
}
`;
}

async function writeProjectFile(target, content, force) {
  await writeFile(target, content, { flag: force ? 'w' : 'wx' });
}

export async function runScaffold({ flags, positional, output }) {
  const name = flags.name ?? positional[0] ?? 'my-earn-app';
  const force = Boolean(flags.force);
  const targetDir = path.resolve(process.cwd(), name);
  const projectName = path.basename(targetDir);
  const packageName = toPackageName(projectName);
  const srcDir = path.join(targetDir, 'src');

  await mkdir(srcDir, { recursive: true });

  try {
    await writeProjectFile(path.join(targetDir, 'package.json'), getProjectPackageJson(packageName), force);
    await writeProjectFile(path.join(targetDir, '.env.example'), 'LIFI_API_KEY=\nEARN_CHAIN_ID=8453\nEARN_ASSET=USDC\n', force);
    await writeProjectFile(path.join(targetDir, 'README.md'), getProjectReadme(projectName), force);
    await writeProjectFile(path.join(srcDir, 'earn.js'), getEarnClientModule(), force);
    await writeProjectFile(path.join(srcDir, 'vaults.js'), getVaultsModule(), force);
    await writeProjectFile(path.join(srcDir, 'index.js'), getProjectEntryPoint(), force);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes('EEXIST')) {
      output.log(`Scaffold aborted: files already exist in ${targetDir}`);
      output.log('Use --force to overwrite scaffold files.');
      return;
    }

    throw error;
  }

  output.log(`Scaffold generated at ${targetDir}`);
  output.log('Run `npm install` then `npm start` inside the generated folder.');
}
