import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

function getProjectPackageJson(name) {
  const packageJson = {
    name,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      start: 'node src/index.js',
    },
  };

  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function getProjectReadme(name) {
  return `# ${name}

Minimal LI.FI Earn starter generated by create-earn-app.

## Setup

1. Copy \`.env.example\` to \`.env\`
2. Add your \`LIFI_API_KEY\`
3. Run \`npm start\`
`;
}

function getProjectEntryPoint() {
  return `const chainId = process.env.EARN_CHAIN_ID ?? '8453';
const asset = process.env.EARN_ASSET ?? 'USDC';

console.log('create-earn-app starter');
console.log('- chainId:', chainId);
console.log('- asset:', asset);
console.log('- next step: wire vault discovery + quote + execute flow');
`;
}

function getEarnClientModule() {
  return `const EARN_BASE_URL = process.env.LIFI_EARN_BASE_URL ?? 'https://earn.li.fi';

export function getEarnHeaders() {
  const headers = {
    Accept: 'application/json',
  };

  if (process.env.LIFI_API_KEY) {
    headers['x-lifi-api-key'] = process.env.LIFI_API_KEY;
  }

  return headers;
}

export function buildEarnUrl(pathname, params = {}) {
  const url = new URL(pathname, EARN_BASE_URL);
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null || value === '') {
      continue;
    }
    url.searchParams.set(key, String(value));
  }
  return url;
}

export async function fetchEarn(pathname, params = {}) {
  const url = buildEarnUrl(pathname, params);
  const response = await fetch(url, { headers: getEarnHeaders() });

  if (!response.ok) {
    throw new Error(\`Earn request failed (\${response.status})\`);
  }

  return response.json();
}
`;
}

async function writeProjectFile(target, content, force) {
  await writeFile(target, content, { flag: force ? 'w' : 'wx' });
}

export async function runScaffold({ flags, positional, output }) {
  const name = flags.name ?? positional[0] ?? 'my-earn-app';
  const force = Boolean(flags.force);
  const targetDir = path.resolve(process.cwd(), name);
  const srcDir = path.join(targetDir, 'src');

  await mkdir(srcDir, { recursive: true });

  try {
    await writeProjectFile(path.join(targetDir, 'package.json'), getProjectPackageJson(name), force);
    await writeProjectFile(path.join(targetDir, '.env.example'), 'LIFI_API_KEY=\nEARN_CHAIN_ID=8453\nEARN_ASSET=USDC\n', force);
    await writeProjectFile(path.join(targetDir, 'README.md'), getProjectReadme(name), force);
    await writeProjectFile(path.join(srcDir, 'earn.js'), getEarnClientModule(), force);
    await writeProjectFile(path.join(srcDir, 'index.js'), getProjectEntryPoint(), force);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes('EEXIST')) {
      output.log(`Scaffold aborted: files already exist in ${targetDir}`);
      output.log('Use --force to overwrite scaffold files.');
      return;
    }

    throw error;
  }

  output.log(`Scaffold generated at ${targetDir}`);
  output.log('Run `npm install` then `npm start` inside the generated folder.');
}
